# Generated by Django 3.2.3 on 2021-07-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210725_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='basictype',
            new_name='basic',
        ),
    ]
