# Generated by Django 3.2.3 on 2021-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_basictype_customer_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='daily',
            field=models.IntegerField(),
        ),
    ]
