# Generated by Django 3.2.3 on 2021-07-28 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_auto_20210728_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='Qna',
        ),
    ]
