# Generated by Django 3.2.3 on 2021-07-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_faq_qna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='faq_body',
            new_name='qna_body',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='faq_date',
            new_name='qna_date',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='faq_title',
            new_name='qna_title',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='faq_no',
        ),
    ]
