# Generated by Django 3.2.3 on 2021-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210728_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='qna_view',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
