# Generated by Django 3.2.3 on 2021-07-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_notices_notice_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='qna_answer',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
