# Generated by Django 3.2.3 on 2021-08-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_attendance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='myclass',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
