# Generated by Django 3.2.3 on 2021-08-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20210808_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.AddField(
            model_name='class',
            name='myclass',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
