# Generated by Django 3.2.3 on 2021-08-08 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0025_auto_20210808_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='myclass',
        ),
        migrations.AddField(
            model_name='class',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
