# Generated by Django 3.2.3 on 2021-08-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210808_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_time',
        ),
    ]
