# Generated by Django 3.2.3 on 2021-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_class_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
